Repository hmcts/sscs-tribunals-case-api, pull requests merged in 2018-12, with the labels that each got.

#337 Do not create preview environments for dependabot
  Jenkinsfile_CNP
Labels: ns:sscs-tribunals-api-pr-337

#345 SSCS-4283 - Update test coverage for same address
  src/e2e/java/uk/gov/hmcts/reform/sscs/functional/ccd/CreateCaseInCcdTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/transform/deserialize/SubmitYourAppealToCcdCaseDataDeserializerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/util/SyaJsonMessageSerializer.java
  src/test/resources/sya/allDetailsWithAppointeeWithDifferentAddressCcd.json
  src/test/resources/sya/allDetailsWithAppointeeWithSameAddress.json
  src/test/resources/sya/allDetailsWithAppointeeWithSameAddressButNoAppellantContactDetailsCcd.json
  src/test/resources/sya/allDetailsWithAppointeeWithSameAddressCcd.json
Labels: ns:sscs-tribunals-api-pr-345

#350 Slf4j revert
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:sscs-tribunals-api-pr-350

#354 SSCS-4659 - upgrade common lib
  build.gradle
Labels: ns:sscs-tribunals-api-pr-354

#343 SSCS-4614 - appointee tya number generation
  build.gradle
  src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/service/RoboticsServiceIt.java
  src/e2e/java/uk/gov/hmcts/reform/sscs/functional/ccd/CreateCaseInCcdTest.java
  src/main/java/uk/gov/hmcts/reform/sscs/domain/wrapper/SyaCaseWrapper.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/AppealNumberGenerator.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealService.java
  src/main/java/uk/gov/hmcts/reform/sscs/transform/deserialize/SubmitYourAppealToCcdCaseDataDeserializer.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/AppealNumberGeneratorTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealServiceTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/transform/deserialize/SubmitYourAppealToCcdCaseDataDeserializerTest.java
  src/test/resources/json/sya.json
  src/test/resources/json/sya_with_evidence.json
  src/test/resources/sya/allDetailsCcd.json
  src/test/resources/sya/allDetailsWithAppointeeWithDifferentAddressCcd.json
  src/test/resources/sya/allDetailsWithAppointeeWithSameAddressButNoAppellantContactDetailsCcd.json
  src/test/resources/sya/allDetailsWithAppointeeWithSameAddressCcd.json
  src/test/resources/sya/appealWithEvidenceDocumentsCcd.json
  src/test/resources/sya/appellantPhoneNumberWithoutSpacesCcd.json
  src/test/resources/sya/hearingWithSupportWithoutScheduleHearingCcd.json
  src/test/resources/sya/hearingWithoutSupportAndScheduleHearingCcd.json
  src/test/resources/sya/hearingWithoutSupportWithScheduleHearingCcd.json
  src/test/resources/sya/ninoWithoutSpacesCcd.json
  src/test/resources/sya/withoutEmailNotificationCcd.json
  src/test/resources/sya/withoutHearingCcd.json
  src/test/resources/sya/withoutNotificationCcd.json
  src/test/resources/sya/withoutRepresentativeCcd.json
  src/test/resources/sya/withoutRpcCcd.json
  src/test/resources/sya/withoutSmsNotificationCcd.json
Labels: ns:sscs-tribunals-api-pr-343
