Repository hmcts/sscs-tribunals-case-api, pull requests merged in 2019-03, with the labels that each got.

#406 set up SSCS tribunals case api security scan
  Jenkinsfile_nightly
  functional-output/.gitkeep
  security.sh
Labels: ns:sscs-tribunals-api-pr-406

#408 use Dockerglue for SSCS tribunals case api security scan
  security.sh
Labels: ns:sscs-tribunals-api-pr-408

#409 Rubyglue for SSCS tribunals case api security scan false positives
  security.sh
Labels: ns:sscs-tribunals-api-pr-409

#411 Sscs 5232 tya surnames
  build.gradle
Labels: DO NOT MERGE, ns:sscs-tribunals-api-pr-411

#362 SSCS-4658: Subscribe a rep to sms notifications if a mobile is entered
  src/main/java/uk/gov/hmcts/reform/sscs/transform/deserialize/SubmitYourAppealToCcdCaseDataDeserializer.java
  src/test/java/uk/gov/hmcts/reform/sscs/transform/deserialize/SubmitYourAppealToCcdCaseDataDeserializerTest.java
  src/test/resources/sya/allDetailsCcd.json
  src/test/resources/sya/allDetailsWithAppointeeWithDifferentAddressCcd.json
  src/test/resources/sya/allDetailsWithAppointeeWithSameAddressButNoAppellantContactDetailsCcd.json
  src/test/resources/sya/allDetailsWithAppointeeWithSameAddressCcd.json
  src/test/resources/sya/appealWithEvidenceDocumentsCcd.json
  src/test/resources/sya/appellantPhoneNumberWithoutSpacesCcd.json
  src/test/resources/sya/hearingWithSupportWithoutScheduleHearingCcd.json
  src/test/resources/sya/hearingWithoutSupportAndScheduleHearingCcd.json
  src/test/resources/sya/hearingWithoutSupportWithScheduleHearingCcd.json
  src/test/resources/sya/ninoWithoutSpacesCcd.json
  src/test/resources/sya/withoutEmailNotificationCcd.json
  src/test/resources/sya/withoutHearingCcd.json
  src/test/resources/sya/withoutNotificationCcd.json
  src/test/resources/sya/withoutRepresentativeCcd.json
  src/test/resources/sya/withoutRpcCcd.json
  src/test/resources/sya/withoutSmsNotificationCcd.json
Labels: ns:sscs-tribunals-api-pr-362

#413 configure tribunal to point to sidam on the saat env
  Jenkinsfile_CNP
  Jenkinsfile_parameterized
  infrastructure/main.tf
  infrastructure/saat.tfvars
  infrastructure/sandbox.tfvars
  kubernetes/deployment.template.yaml
Labels: ns:sscs-tribunals-api-pr-413

#410 SSCS-4442: Generate a tya number when no rep
  src/main/java/uk/gov/hmcts/reform/sscs/transform/deserialize/SubmitYourAppealToCcdCaseDataDeserializer.java
  src/test/java/uk/gov/hmcts/reform/sscs/transform/deserialize/SubmitYourAppealToCcdCaseDataDeserializerTest.java
Labels: ns:sscs-tribunals-api-pr-410

#419 Upgrade common pdf library to 0.0.106
  build.gradle
  src/test/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealServiceTest.java
Labels: ns:sscs-tribunals-api-pr-419

#425 fix gradlew functional task to make functional tests run in the pipeline
  build.gradle
Labels: ns:sscs-tribunals-api-pr-425

#424 SSCS-5162 Internal server error - propagating error message to Front End
  build.gradle
  src/main/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealService.java
Labels: ns:sscs-tribunals-api-pr-424

#435 Upgrade pdf common to 0.0.108
  build.gradle
Labels: ns:sscs-tribunals-api-pr-435

#426 set up SSCS tribunals case api security scan
  functional-output/glue.json
  security.sh
Labels: ns:sscs-tribunals-api-pr-426

#444 SSCS-5231 Tweaks to SYA Report
  build.gradle
  src/main/java/uk/gov/hmcts/reform/sscs/controller/SyaController.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealService.java
Labels: ns:sscs-tribunals-api-pr-444
