Repository hmcts/sscs-tribunals-case-api, pull requests merged in 2022-04, with the labels that each got.

#2650 Update build.gradle
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-api-pr-2650

#2649 Sscs 10220 create hearings event queue new
  Jenkinsfile_CNP
  build.gradle
  charts/sscs-tribunals-api/Chart.yaml
  charts/sscs-tribunals-api/values.yaml
  dependency-check-suppressions.xml
  dump.rdb
  infrastructure/resource-group.tf
  infrastructure/service-bus.tf
  infrastructure/variables.tf
  src/main/java/uk/gov/hmcts/reform/sscs/TribunalsCaseApiApplication.java
  src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/readytolist/HearingHandler.java
  src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/readytolist/ReadyToListAboutToSubmitHandler.java
  src/main/java/uk/gov/hmcts/reform/sscs/config/HearingServiceBusClientConfig.java
  src/main/java/uk/gov/hmcts/reform/sscs/controller/CcdCallbackController.java
  src/main/java/uk/gov/hmcts/reform/sscs/controller/CcdMideventCallbackController.java
  src/main/java/uk/gov/hmcts/reform/sscs/controller/CitizenController.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/servicebus/HearingMessagingServiceFactory.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/servicebus/SessionAwareServiceBusMessagingService.java
  src/main/resources/config/application.properties
  src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/readytolist/ReadyToListAboutToSubmitHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/controller/CcdCallbackControllerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/controller/CcdMideventCallbackControllerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/servicebus/hearings/HearingMessagingServiceFactoryTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-api-pr-2649

#2653 SSCS-10220 Fix resource group.
  infrastructure/resource-group.tf
  infrastructure/service-bus.tf
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-api-pr-2653

#2657 Update commons
  build.gradle
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-api-pr-2657

#2662 SSCS-10376 Fix Suppressions
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-api-pr-2662

#2663 suppress security fix
  audit.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-api-pr-2663

#2637 Sscs 10146 add 2 specialisms to case
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-api-pr-2637

#2660 SSCS-10387 Update Commons
  build.gradle
  src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/readytolist/HearingHandler.java
  src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/readytolist/ReadyToListAboutToSubmitHandlerTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-api-pr-2660

#2678 Update sprintboot core
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-api-pr-2678
