Repository hmcts/sscs-tribunals-case-api, pull requests merged in 2022-02, with the labels that each got.

#2555 SSCS-9902: Location data – Update airlookup to v15
  build.gradle
  src/IntegrationTests/java/uk/gov/hmcts/reform/sscs/callback/CaseUpdatedIt.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/RestoreCasesService2Test.java
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-api-pr-2555

#2558 SSCS-9902 Increase Jakarta CVE supperesion by one month.
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-api-pr-2558

#2560 SSCS - 10099 - tribunals integration test fail
  src/test/resources/json/sya.json
  src/test/resources/json/sya_with_benefit_type.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-api-pr-2560

#2532 update tribunels with new sscs-commons version
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-api-pr-2532

#2566 surpress dependencies
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-api-pr-2566

#2527 Sscs 9944 change dwp to fta
  build.gradle
  src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandler.java
  src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/createbundle/CreateBundleAboutToStartEventHandler.java
  src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/createbundle/CreateBundleAboutToSubmitHandler.java
  src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseAboutToSubmitHandler.java
  src/main/java/uk/gov/hmcts/reform/sscs/model/AppConstants.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/SubmitAppealService.java
  src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/createbundle/CreateBundleAboutToStartEventHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/dwpuploadresponse/DwpUploadResponseAboutToSubmitHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceAboutToSubmitHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/hmctsresponsereviewed/HmctsResponseReviewedAboutToSubmitHandlerTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-api-pr-2527

#2562 SSCS - 10070 - Change data in 'caseAccessCategory' field
  build.gradle
  src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/caseupdated/CaseUpdatedAboutToSubmitHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/transform/deserialize/SubmitYourAppealToCcdCaseDataDeserializerTest.java
  src/test/resources/sya/allDetailsFromDraftCcd.json
  src/test/resources/sya/allDetailsFromDraftNoMrnDateCcd.json
  src/test/resources/sya/allDetailsFromDraftWithInterlocCcd.json
  src/test/resources/sya/allDetailsNonSaveAndReturnCcd.json
  src/test/resources/sya/allDetailsNonSaveAndReturnCcdChildSupport.json
  src/test/resources/sya/allDetailsNonSaveAndReturnCcdSscs5.json
  src/test/resources/sya/allDetailsNonSaveAndReturnNoMrnDateCcd.json
  src/test/resources/sya/allDetailsNonSaveAndReturnWithInterlocCcd.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-api-pr-2562

#2554 SSCS-9878 Enable other party options for sscs5 cases
  src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/subscriptionupdated/SubscriptionUpdatedAboutToSubmitHandler.java
  src/main/java/uk/gov/hmcts/reform/sscs/util/PartiesOnCaseUtil.java
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-api-pr-2554

#2588 Upgrade secuirty dependency
  dependency-check-suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-api-pr-2588

#2322 SSCS-9550 - Retry on create appeal
  build.gradle
  src/main/java/uk/gov/hmcts/reform/sscs/TribunalsCaseApiApplication.java
  src/main/java/uk/gov/hmcts/reform/sscs/config/CitizenCcdClient.java
  src/main/java/uk/gov/hmcts/reform/sscs/config/CitizenCcdService.java
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-api-pr-2322

#2586 updating log4j to version 2.17
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-api-pr-2586

#2590 rollback change
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-api-pr-2590

#2591 Update build.gradle p2 fix - will back out later
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-api-pr-2591

#2592 Update build.gradle - revert p2-deploy-fix
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-api-pr-2592

#2594 scss-10288-changes breaking the integration tests are reverted
  audit.json
  src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/SubmitAppealTest.java
  src/e2e/java/uk/gov/hmcts/reform/sscs/functional/sya/SubmitDraftTest.java
  src/test/resources/sya/allDetailsNonSaveAndReturnCcdSscs5.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-api-pr-2594

#2596 Sscs 10018 process audio video
  build.gradle
  src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/processaudiovideo/ProcessAudioVideoActionDynamicListItems.java
  src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/processaudiovideo/ProcessAudioVideoActionHelper.java
  src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/processaudiovideo/ProcessAudioVideoEvidenceAboutToSubmitHandler.java
  src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/procesaudiovideo/ProcessAudioVideoEvidenceAboutToSubmitHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/procesaudiovideo/ProcessAudioVideoEvidenceMidEventHandlerTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-api-pr-2596
