Repository hmcts/sscs-tribunals-case-api, pull requests merged in 2023-02, with the labels that each got.

#3135 SSCS-11249 - jenkins minor change
  Jenkinsfile_CNP
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-api-pr-3135

#3058 SSCS-10295: change interpreter language type to DynamicList
  build.gradle
  config/owasp/suppressions.xml
  src/functionalTest/java/uk/gov/hmcts/reform/sscs/functional/handlers/adjourncase/AdjournCaseAboutToSubmitHandlerTest.java
  src/functionalTest/resources/handlers/adjourncase/adjournCaseGapsCallback.json
  src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCaseAboutToStartHandler.java
  src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCaseAboutToSubmitHandler.java
  src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCasePreviewService.java
  src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceAboutToSubmitHandler.java
  src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/updatelistingrequirements/UpdateListingRequirementsAboutToStartHandler.java
  src/main/java/uk/gov/hmcts/reform/sscs/service/LanguageService.java
  src/main/java/uk/gov/hmcts/reform/sscs/util/DynamicListLanguageUtil.java
  src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCaseAboutToStartHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCaseAboutToSubmitHandlerMainTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCaseAboutToSubmitHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCaseMidEventValidationHandlerMainTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCasePreviewServiceTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceAboutToSubmitHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/issueadjournment/IssueAdjournmentNoticeAboutToSubmitHandlerTestBase.java
  src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/updatelistingrequirements/UpdateListingRequirementsAboutToStartHandlerTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/LanguageServiceTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/service/adjourncase/AdjournCaseServiceTest.java
  src/test/java/uk/gov/hmcts/reform/sscs/util/DynamicListLanguageUtilTest.java
  src/test/resources/callback/adjournCaseGeneratedFaceToFaceWithInterpreterRequiredAndLanguageSet.json
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-api-pr-3058

#3124 SSCS-10539 - Tribunals changes to allow new set aside application changes in action further evidence
  src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceAboutToSubmitHandler.java
  src/test/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/furtherevidence/actionfurtherevidence/ActionFurtherEvidenceAboutToSubmitHandlerTest.java
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-api-pr-3124

#3130 update to use new commons
  build.gradle
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-api-pr-3130

#3142 SSCS-11396 - Unable to submit write adjournment notice event
  src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/adjourncase/AdjournCaseAboutToSubmitHandler.java
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-api-pr-3142

#3148 SSCS-10316 - upgrade sscs-common to v4.25.2
  build.gradle
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-api-pr-3148

#3150 SSCS-11393 : Removed log line causing NPE
  src/main/java/uk/gov/hmcts/reform/sscs/ccd/presubmit/updatelistingrequirements/UpdateListingRequirementsAboutToStartHandler.java
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-api-pr-3150

#3160 SSCS-11188 - Upgrade TF 0.13.X to 0.14.X
  charts/sscs-tribunals-api/Chart.yaml
  charts/sscs-tribunals-api/values.ccd.preview.template.yaml
  infrastructure/.terraform-version
Labels: ns:sscs, prd:sscs, add-or-update, rel:sscs-tribunals-api-pr-3160

#3161 SSCS-11188 - Upgrade TF 0.14.X to 0.15.X
  infrastructure/.terraform-version
  infrastructure/variables.tf
Labels: ns:sscs, prd:sscs, no-changes, rel:sscs-tribunals-api-pr-3161

#3162 SSCS-11188 - Upgrade TF 0.15.X to 1.3.X
  infrastructure/.terraform-version
Labels: ns:sscs, prd:sscs, no-changes, rel:sscs-tribunals-api-pr-3162

#3167 suppresses CVE-2022-45688
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-api-pr-3167
