Repository hmcts/sscs-tribunals-case-api, pull requests merged in 2024-05, with the labels that each got.

#3795 Suppression date fix
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-api-pr-3795

#3793 Fix preview deployment
  Jenkinsfile_CNP
  charts/sscs-tribunals-api/Chart.yaml
  charts/sscs-tribunals-api/values.ccd.preview.template.yaml
  charts/sscs-tribunals-api/values.wa.preview.template.yaml
Labels: ns:sscs, prd:sscs, pr-values:ccd, rel:sscs-tribunals-api-pr-3793

#3809 Fix NullPointerException
  charts/sscs-tribunals-api/values.ccd.preview.template.yaml
  charts/sscs-tribunals-api/values.wa.preview.template.yaml
  src/main/java/uk/gov/hmcts/reform/sscs/util/AddedDocumentsUtil.java
Labels: ns:sscs, prd:sscs, pr-values:ccd, rel:sscs-tribunals-api-pr-3809

#3830 SSCSSI-245 | Fix Nightly evidence share tests
  Jenkinsfile_nightly
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-api-pr-3830

#3834 SSCSCI-874 Update suppression date
  config/owasp/suppressions.xml
Labels: ns:sscs, prd:sscs, rel:sscs-tribunals-api-pr-3834
